In [17]:
# Import the dependencies.
import pandas as pd 
import gmaps
import requests

# Import the API key.
from config import g_key

In [18]:
# Store the CSV you saved created in part one into a Dataframe.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Pemangkat,ID,2022-07-13 01:00:07,1.1667,108.9667,79.99,79,100,4.03
1,1,Ribeira Grande,PT,2022-07-13 01:00:07,38.5167,-28.7000,70.23,91,96,8.70
2,2,Lorengau,PG,2022-07-13 01:00:08,-2.0226,147.2712,85.01,70,28,9.86
3,3,Canto Do Buriti,BR,2022-07-13 01:00:08,-8.1100,-42.9444,75.31,45,14,4.59
4,4,Carnarvon,AU,2022-07-13 01:00:09,-24.8667,113.6333,68.70,65,6,8.75

In [19]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [20]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [21]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp,0))

In [22]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0,31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp,0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [23]:
# Heatmap of percent humidity 
locations = city_data_df[["Lat","Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0,31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [24]:
# Heatmap of percent cloudiness.
locations = city_data_df[["Lat","Lng"]]
clouds = city_data_df["Cloudiness"]
fig= gmaps.figure(center=(30.0,31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [25]:
# Heatmap of Wind Speed (mph)
locations = city_data_df[["Lat","Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0,31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [26]:
# Ask the customer to add a minimum and maximum temperature value. 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [27]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Pemangkat,ID,2022-07-13 01:00:07,1.1667,108.9667,79.99,79,100,4.03
2,2,Lorengau,PG,2022-07-13 01:00:08,-2.0226,147.2712,85.01,70,28,9.86
3,3,Canto Do Buriti,BR,2022-07-13 01:00:08,-8.1100,-42.9444,75.31,45,14,4.59
6,6,Port Blair,IN,2022-07-13 01:00:10,11.6667,92.7500,82.02,82,100,19.82
7,7,Hithadhoo,MV,2022-07-13 01:00:10,-0.6000,73.0833,83.41,72,17,13.62
14,14,Bethel,US,2022-07-13 01:00:15,41.3712,-73.4140,77.83,95,100,9.84
18,18,Hambantota,LK,2022-07-13 01:00:17,6.1241,81.1185,77.34,94,20,8.05
20,20,Vaini,TO,2022-07-13 01:00:18,-21.2000,-175.2000,76.59,73,1,13.53
22,22,Alofi,NU,2022-07-13 01:00:19,-19.0595,-169.9187,78.28,77,22,23.02
25,25,Zhoucheng,CN,2022-07-13 01:00:21,35.9122,116.3117,80.47,77,94,5.64

In [28]:
preferred_cities_df.count()

City_ID       197
City          197
Country       197
Date          197
Lat           197
Lng           197
Max Temp      197
Humidity      197
Cloudiness    197
Wind Speed    197
dtype: int64

In [44]:
# Create Dataframe called hotel_df to store hotel names along with city,country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City","Country","Max Temp","Lat","Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

               City Country  Max Temp      Lat       Lng Hotel Name
0         Pemangkat      ID     79.99   1.1667  108.9667
2          Lorengau      PG     85.01  -2.0226  147.2712
3   Canto Do Buriti      BR     75.31  -8.1100  -42.9444
6        Port Blair      IN     82.02  11.6667   92.7500
7         Hithadhoo      MV     83.41  -0.6000   73.0833
14           Bethel      US     77.83  41.3712  -73.4140
18       Hambantota      LK     77.34   6.1241   81.1185
20            Vaini      TO     76.59 -21.2000 -175.2000
22            Alofi      NU     78.28 -19.0595 -169.9187
25        Zhoucheng      CN     80.47  35.9122  116.3117

In [43]:
# Set parameters to search for a hotel.
#params = {"radius": 5000,
      #   "types": "lodging",
      #   "key": g_key,
      #   "location": "48.8566,2.3522"}


# use iterrows() function to iterate through hotel_df dataframe.
#for index,row in hotel_df.iterrows():
    # Get the latitude and longitude.
   # lat = row["Lat"]
   # lng = row["Lng"]
    
    # Add the latitude and longitude to location key for the params dictionary.
   # params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
   # base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make a request and get the JSON data from the search.
   # hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name.
    # if look in google_nearby_search.ipynb will see JSON dictionary list 
    # this is how knew which 'key' to input to equal to loc method w/o having to review json dictionary data
   # hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    
# this cell gets error code on purpose 
# next cell shows how to fix with try-except block

In [85]:
# Set parameters to search for a hotel.
params = {"radius": 5000,
         "types": "lodging",
         "key": g_key,
         }

# use iterrows() function to iterate through hotel_df dataframe.
for index,row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make a request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
     # Grab the first hotel from the results and store the name.
    try: 
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found...skipping.")

Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.

In [86]:
hotel_df.head(35)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Pemangkat,ID,79.99,1.1667,108.9667,Ramah Kost KITA
2,Lorengau,PG,85.01,-2.0226,147.2712,Lorengau Harbourside Hotel
3,Canto Do Buriti,BR,75.31,-8.1100,-42.9444,Novo Hotel
6,Port Blair,IN,82.02,11.6667,92.7500,"Welcomhotel By ITC Hotels, Bay Island, Port Blair"
7,Hithadhoo,MV,83.41,-0.6000,73.0833,Scoop Guest House
14,Bethel,US,77.83,41.3712,-73.4140,Courtyard by Marriott Danbury
18,Hambantota,LK,77.34,6.1241,81.1185,Bungalow 63
20,Vaini,TO,76.59,-21.2000,-175.2000,Keleti Beach Resort
22,Alofi,NU,78.28,-19.0595,-169.9187,Taloa Heights
25,Zhoucheng,CN,80.47,35.9122,116.3117,Yingbin Restaurant
26,Dusti,TJ,75.56,37.3481,68.6640,Hotel Izzat
27,Atuona,PF,77.77,-9.8000,-139.0333,Villa Enata
30,Hilo,US,86.29,19.7297,-155.0900,Hilo Hawaiian Hotel
38,Shingu,JP,84.43,33.7333,135.9833,Shingu UI Hotel
39,Yakovlevka,RU,80.80,44.4250,133.4772,NaN
42,Auki,SB,85.60,-8.7676,160.7034,Auki Motel
45,Fairbanks,US,78.60,64.8378,-147.7164,Westmark Fairbanks Hotel & Conference Center
46,Kandrian,PG,85.17,-6.2167,149.5500,Kandrian Station
47,Tual,ID,78.76,-5.6667,132.7500,Grand Vilia Hotel
49,Gazanjyk,TM,79.14,39.2446,55.5154,Railway motel
51,Albany,US,75.88,42.6001,-73.9662,NaN
57,Kalmunai,LK,77.22,7.4167,81.8167,VS Villa
63,Butaritari,KI,82.44,3.0707,172.7902,Isles Sunset Lodge
65,West Wendover,US,84.13,40.7391,-114.0733,"Motel 6 Wendover, UT"
67,Rikitea,PF,75.13,-23.1203,-134.9692,People ThankYou
74,Kapaa,US,84.18,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
86,Padang,ID,78.93,-0.9492,100.3543,Mercure Padang
87,Thompson,CA,77.16,55.7435,-97.8558,Burntwood Hotel
89,Vaitape,PF,78.78,-16.5167,-151.7500,Conrad Bora Bora Nui
90,Avarua,CK,75.25,-21.2078,-159.7750,Paradise Inn
91,Mandera,KE,75.09,3.9366,41.8670,Red Sea Resort & Suites Mandera County
96,Weinan,CN,76.35,34.5036,109.5089,Thank Inn Chain Hotel shanxi weinan linwei dis...
104,Puerto Escondido,MX,79.63,15.8500,-97.0667,Aldea del Bazar Hotel and Spa
105,Georgetown,MY,78.73,5.4112,100.3354,Cititel Penang
106,Aripuana,BR,75.78,-9.1667,-60.6333,NaN

In [100]:
new_hotel_df = hotel_df.dropna()

In [101]:
new_hotel_df.head(35)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Pemangkat,ID,79.99,1.1667,108.9667,Ramah Kost KITA
2,Lorengau,PG,85.01,-2.0226,147.2712,Lorengau Harbourside Hotel
3,Canto Do Buriti,BR,75.31,-8.1100,-42.9444,Novo Hotel
6,Port Blair,IN,82.02,11.6667,92.7500,"Welcomhotel By ITC Hotels, Bay Island, Port Blair"
7,Hithadhoo,MV,83.41,-0.6000,73.0833,Scoop Guest House
14,Bethel,US,77.83,41.3712,-73.4140,Courtyard by Marriott Danbury
18,Hambantota,LK,77.34,6.1241,81.1185,Bungalow 63
20,Vaini,TO,76.59,-21.2000,-175.2000,Keleti Beach Resort
22,Alofi,NU,78.28,-19.0595,-169.9187,Taloa Heights
25,Zhoucheng,CN,80.47,35.9122,116.3117,Yingbin Restaurant
26,Dusti,TJ,75.56,37.3481,68.6640,Hotel Izzat
27,Atuona,PF,77.77,-9.8000,-139.0333,Villa Enata
30,Hilo,US,86.29,19.7297,-155.0900,Hilo Hawaiian Hotel
38,Shingu,JP,84.43,33.7333,135.9833,Shingu UI Hotel
42,Auki,SB,85.60,-8.7676,160.7034,Auki Motel
45,Fairbanks,US,78.60,64.8378,-147.7164,Westmark Fairbanks Hotel & Conference Center
46,Kandrian,PG,85.17,-6.2167,149.5500,Kandrian Station
47,Tual,ID,78.76,-5.6667,132.7500,Grand Vilia Hotel
49,Gazanjyk,TM,79.14,39.2446,55.5154,Railway motel
57,Kalmunai,LK,77.22,7.4167,81.8167,VS Villa
63,Butaritari,KI,82.44,3.0707,172.7902,Isles Sunset Lodge
65,West Wendover,US,84.13,40.7391,-114.0733,"Motel 6 Wendover, UT"
67,Rikitea,PF,75.13,-23.1203,-134.9692,People ThankYou
74,Kapaa,US,84.18,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
86,Padang,ID,78.93,-0.9492,100.3543,Mercure Padang
87,Thompson,CA,77.16,55.7435,-97.8558,Burntwood Hotel
89,Vaitape,PF,78.78,-16.5167,-151.7500,Conrad Bora Bora Nui
90,Avarua,CK,75.25,-21.2078,-159.7750,Paradise Inn
91,Mandera,KE,75.09,3.9366,41.8670,Red Sea Resort & Suites Mandera County
96,Weinan,CN,76.35,34.5036,109.5089,Thank Inn Chain Hotel shanxi weinan linwei dis...
104,Puerto Escondido,MX,79.63,15.8500,-97.0667,Aldea del Bazar Hotel and Spa
105,Georgetown,MY,78.73,5.4112,100.3354,Cititel Penang
107,Rosarito,MX,77.41,32.3333,-117.0333,Hotel Festival Plaza Rosarito
114,Isangel,VU,80.22,-19.5500,169.2667,Tanna Lodge
115,Faanui,PF,78.76,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa

In [102]:
new_hotel_df.count()

City          179
Country       179
Max Temp      179
Lat           179
Lng           179
Hotel Name    179
dtype: int64

In [104]:
# Add a heatmap of temperature for the vacation spots.
locations = new_hotel_df[["Lat", "Lng"]]
max_temp = new_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)

fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [105]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [108]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in new_hotel_df.iterrows()]

In [111]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = new_hotel_df[["Lat", "Lng"]]
max_temp = new_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))